stages:
  - test
  - deploy

default:
  image: node:20.16.0

cache:
  paths:
    - node_modules/

prettier-test-job:
  stage: test
  script:
    - npm run check

deploy-job:
  stage: deploy
  environment: production

  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_NAME: $DOCKER_USERNAME/experiments

  before_script:
    - mkdir /etc/gitlab-runner/
    - mv config.toml /etc/gitlab-runner/
    - mkdir ~/.docker
    - echo $DOCKER_AUTH_CONFIG | base64 -d > ~/.docker/config.json
    - until docker info; do sleep 1; done;

  script:
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker push $DOCKER_IMAGE_NAME:latest

  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
