image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_IMAGE_NAME: $DOCKER_USERNAME/experiments

before_script:
  - mkdir ~/.docker
  - echo $DOCKER_AUTH_CONFIG | base64 -d > ~/.docker/config.json
  - until docker info; do sleep 1; done;

build-master:
  stage: build
  script:
    - docker build --pull -t $DOCKER_IMAGE_NAME:latest .
    - docker push $DOCKER_IMAGE_NAME:latest

